[package]
name = "tugos"
version = "0.1.0"
authors = ["Tushar R. Gosavi <tushargosavi@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"

[profile.dev]
panic = "abort"

# The release profile, used for `cargo build --release`.
[profile.release]
panic = "abort"

